### ISSUE TITLE
bad interpreter: /bin/env: no such file or directory

### ISSUE THREAD

**Issue by pavelsevcik** [duzun/verup#2]
verup: 1.6.1-b
os: Linux Mint 18.1

`#!/bin/env node` at https://github.com/duzun/verup/blame/master/dist/verup.js#L1 causing `bad interpreter: /bin/env: no such file or directory`

`#!/usr/bin/env node` works

**Comment by duzun** [comment]
Fixed in 785de3d425673e8e708805f16da9b42b9ccf0a71
Thanks @pavelsevcik !
